name: release-please

# https://github.com/marketplace/actions/release-please-action
# https://github.com/googleapis/release-please

on:
  push:
    branches:
      - main
      - chi

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          target-branch: ${{ github.ref_name }}
          # optional. customize path to release-please-config.json
          config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: release-please-config.json
          token: ${{ secrets.RELEASE_ACTION_GIT_ACCESS_TOKEN }}