name: release-please

# https://github.com/marketplace/actions/release-please-action
# https://github.com/googleapis/release-please

on:
  push:
    branches:
      - main
      - chi

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: release
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          token: ${{ secrets.RELEASE_ACTION_GIT_ACCESS_TOKEN }}